#!/bin/bash
#

# 1. Get some tools we need (please read tools/0README for full instructions!):
#
cd tools
bash 0README
cd ..
export PATH=$PATH:${PWD}/tools

# 2. Download data we need for the usage examples:
#
#
xgainsaw download -i data_sources.txt -D downloads
sleep 30

# 3. Use xgainsaw to populate the data directory:
#
xgainsaw prepare -q mm10 \
	-f downloads/mm10/mm10.fa.gz \
	-z downloads/mm10/mm10.chrom.sizes \
	-A downloads/mm10/chromAlias.txt.gz \
	-C downloads/mm10 \
	-d data -c work.conf
xgainsaw prepare -q mm39 \
	-f downloads/mm39/mm39.fa.gz \
	-z downloads/mm39/mm39.chrom.sizes \
	-a downloads/mm39/GCF_000001635.27_GRCm39_genomic.gff.gz \
	-A downloads/mm39/chromAlias.txt.gz \
	-C downloads/mm39 \
	-d data -c work.conf
xgainsaw prepare -q rn7 \
	-f downloads/rn7/rn7.fa.gz \
	-z downloads/rn7/rn7.chrom.sizes \
	-a downloads/rn7/GCF_015227675.2_mRatBN7.2_genomic.gff.gz \
	-A downloads/rn7/rn7.chromAlias.txt \
	-C downloads/rn7 \
	-d data -c work.conf

# 4. Pull the chr5 and chr7 data from mm39ToRn7.over.chain.gz for use in the
#    test examples:
#
chainFilter -t=chr5,chr7 data/liftovers/mm39ToRn7.over.chain.gz > data/liftovers/mm39chr5and7ToRn7.over.chain

# 5. Make the tools accessible. You may want to include the following into your
#    ~/.bashrc script (or equivalent):
#
echo -e "\n\nPlease execute the following in your working shell to make the downloaded"
echo -e "tools accessible. You may want to add this command to your ~/.bashrc"
echo -e "(or equivalent) file for future use:\n"
echo -e 'export PATH=$PATH:${PWD}/tools'
echo -e "\n\n"
